### ISSUE TITLE
Use GLOBAL_POSITION_INT message type for data updates

### ISSUE THREAD

**Issue by pgiacalo** [wiseman/mavelous#48] opened 2013-01-31 06:45 UTC
Mavelous is using mavlink message type GPS_RAW_INT rather than GLOBAL_POSITION_INT for data updates. 

The mavlink web site has this to saw about GPS_RAW_INT...

"The global position, as returned by the Global Positioning System (GPS).
This is NOT the global position estimate of the sytem, but rather a RAW
sensor value. See message GLOBAL_POSITION for the global position
estimate..."

**Comment by pchickey** [comment] 2013-01-31 06:48
my fault for not seeing my email straight, this is a dupe of #47 ...

**Closed as completed by pchickey** 2013-01-31 06:48 UTC
