### ISSUE TITLE
Enhancement request for ADS-B data

### ISSUE THREAD

**Issue by pgiacalo** [wiseman/mavelous#46] opened 2013-01-22 15:52 UTC
Hi guys,

Would it be possible to enhance mavelous to display multiple aircraft on the map? The need is to show the subject aircraft as well as the other aircraft in the surrounding airspace for situational awareness and collision avoidance. 

Does it seem logical that a new mavlink message type -- comprised of a list of GPS_RAW_INT or GLOBAL_POSITION_INT messages -- would be required? Also, since the subject aircraft needs to be uniquely identified, it would likely need to be the first or last record in the list, correct? 

I'm sure you are busy, but I'm wondering if you see this as doable and how to possibly move forward. 

Thanks,
Phil

**Comment by pchickey** [comment] 2013-01-23 18:12
We could implement this pretty easily once a mavlink message is defined for it, but I don't know enough about the problem to really help design such a message. If you need a unique identifier for certain aircraft, you can possibly give them a numbered tag in the same structure as their location information, and we can display that number or some label that corresponds to it (say, 0 is always the test subject).

**Comment by pchickey** [comment] 2013-01-23 18:13
closed as duplicate of #36

**Closed as completed by pchickey** 2013-01-23 18:13 UTC
Labels: enhancement
